[project]
name = "llmsfs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
  "torch==2.13.0",
  "torchvision==0.28.0",
  "tensorflow==2.21.0",
  "jupyterlab==4.6.2",
  "tiktoken==0.13.0",
  "matplotlib==3.11.1",
  "tqdm==4.70.0",
  "numpy==2.5.1",
  "pandas==3.0.5",
  "pip==26.2.1",
  "psutil==7.2.2",
  "pytest==9.1.1",
  "gymnasium[classic-control]>=1.3.0",
  "seaborn>=0.13.2",
]

[dependency-groups]
dev = [
    "build==1.5.0",
    "ruff==0.16.2",
    "setuptools==84.0.0",
    "twine==7.0.0",
    "tokenizers==0.22.2",
    "safetensors==0.8.0",
]
bonus = [
    "blobfile==3.2.0",
    "chainlit==2.11.1",
    "huggingface_hub==1.27.0",
    "ipywidgets==8.1.8",
    "openai==2.53.0",
    "requests==2.34.2",
    "safetensors==0.8.0",
    "scikit-learn==1.9.0",
    "sentencepiece==0.2.2",
    "thop==0.1.1.post2209072238",
    "tokenizers==0.22.2",
    "transformers==5.14.1",
    "tqdm==4.70.0",
]

[tool.uv]
package = false

[tool.ruff]
line-length = 140

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
exclude = [".venv"]
ignore = [
    "C406", "E226", "E402", "E702", "E703",
    "E722", "E731", "E741"
]
